name: Decathlon CI


on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Bygg med Maven
        run: mvn clean install

      - name: Kör tester
        run: mvn test

